### ISSUE TITLE
question about temperror in spf

### ISSUE THREAD

**Issue by iamDonkey** [andris9/mailauth#2]
hi @andris9 Thanks for your great libraries,

if a domain dns server does not return any TXT record does that mean we should **always** get `temperror` ?
in the result object i am getting status as `temperror` , in comment  dns error code `ENODATA `

**Comment by andris9** [comment]
Could you try v1.0.16 and see if the status is still "temperror"?

**Comment by iamDonkey** [comment]
status is now none 😍
