### ISSUE TITLE
SPF DNS lookup limit capabilities

### ISSUE THREAD

**Issue by amit777** [andris9/mailauth#5]
the RFC for SPF defines a  DNS lookup limit of 10.  It seems like the current SPF validation check does not detect that.

**Describe the solution you'd like**
Have a correct SPF softfail if there are over 10 lookups.  Also, it would be great to have
1. an option to arbitrarily change the lookup limit to more than 10 for testing. 
2. The validation result to report on how many DNS lookups were used

https://github.com/mediamonks/node-spf-check is an older project that has some code related to handling lookup limits.

**Comment by andris9** [comment]
SPF DNS lookup limit is 50 by default. If you want to use another value you can use `maxResolveCount` option like this:

```
const { spf } = require('mailauth/lib/spf');

let result = await spf({
    sender: 'andris@wildduck.email',
    ip: '217.146.76.20',
    helo: 'foo',
    mta: 'mx.myhost.com',
    maxResolveCount:10
});
```

TBH I'm not 100% sure how well the dns  resolve limitation works as compared to RFC, that's why the limit is higher by default. Would be great if you could test it and report back if it is working as it is supposed to.

**Comment by andris9** [comment]
I documentent the `maxResolveCount` limit option in the [README](https://github.com/andris9/mailauth#authentication) as it was missing from there. Also added lookup counters to SPF results, see the `lookups` property in this example verification result:

```
{
  domain: 'wildduck.email',
  'client-ip': '127.0.0.1',
  helo: 'foo',
  'envelope-from': 'andris@wildduck.email',
  rr: 'v=spf1 mx a -all',
  status: {
    result: 'fail',
    comment: 'andrisreinman: domain of andris@wildduck.email does not designate 127.0.0.1 as permitted sender',
    smtp: { mailfrom: 'andris@wildduck.email', helo: 'foo' }
  },
  header: 'Received-SPF: fail (andrisreinman: domain of andris@wildduck.email does not designate 127.0.0.1 as permitted sender) client-ip=127.0.0.1;',
  info: 'spf=fail (andrisreinman: domain of andris@wildduck.email does not designate 127.0.0.1 as permitted sender) smtp.mailfrom=andris@wildduck.email smtp.helo=foo',
  lookups: { limit: 50, count: 4 }
}
```
