### ISSUE TITLE
mailauth reports `dkim=none` although DKIM signature exists and is valid for some emails

### ISSUE THREAD

**Issue by skomski** [andris9/mailauth#6]
dkimpy reports a valid signature for the following email but mailauth reports dkim=none which is false:

[die_welt_email.txt](https://github.com/andris9/mailauth/files/7013142/die_welt_email.txt)

**Comment by andris9** [comment]
v2.1.2 should fix this. Mailauth defaulted to _relaxed/relaxed_ canonicalization if `c=` tag was not present in the DKIM header. Should have been _simple/simple_
